src-vendor/JointPurchaseBundle/Entity/JointPurchase.php
<?php

declare(strict_types=1);

namespace Coop\JointPurchaseBundle\Entity;

use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;

/**
 * Совместные закупки (JointPurchase)
 *
 * @ORM\Entity()
 * @ORM\Table(name="joint_purchases",
 *      indexes={
 *          @ORM\Index(columns={"created_at"}),
 *      }
 * )
 *
 * @ORM\HasLifecycleCallbacks()
 */
class JointPurchase
{
    use ColumnTrait\Uuid;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\UpdatedAt;
    use ColumnTrait\TitleNotBlank;
    use ColumnTrait\Description;

    const STATUS_DRAFT      = 0;
    const STATUS_OPEN       = 1;
    const STATUS_CLOSE      = 2;
    const STATUS_COMPLETE   = 3;
    static protected $status_values = [
        self::STATUS_DRAFT      => 'Черновик',
        self::STATUS_OPEN       => 'Открыто',
        self::STATUS_CLOSE      => 'Закрыто',
        self::STATUS_COMPLETE   => 'Завершено',
    ];

    const SHIPPING_TYPE_NONE     = 0;
    const SHIPPING_TYPE_PER_ITEM = 1;
    const SHIPPING_TYPE_PERCENT  = 2;
    static protected $shipping_type_values = [
        self::SHIPPING_TYPE_NONE     => 'Нет',
        self::SHIPPING_TYPE_PER_ITEM => 'Оплата за еденицу товара',
        self::SHIPPING_TYPE_PERCENT  => 'Процент от заказа',
    ];

    /**
     * Срок формирования заказа (финальная дата) он же “стоп”
     *
     * @var \DateTime
     *
     * @ORM\Column(type="date", nullable=false)
     */
    protected $final_date;

    /**
     * @var int
     *
     * @ORM\Column(type="smallint", nullable=false, options={"unsigned"=true, "default":0})
     */
    protected $status;

    /**
     * Тип лоставки
     *
     * @var int
     *
     * @ORM\Column(type="smallint", nullable=false, options={"unsigned"=true, "default":0})
     *
     * @deprecated
     */
    protected $shipping_type;

    /**
     * Транспортные расходы в процентах
     *
     * @var int|null
     *
     * @ORM\Column(type="integer", nullable=true, options={"unsigned"=true})
     */
    protected $transportation_cost_in_percent;

    /**
     * Ссылка на чат в телеграм
     *
     * @var string|null
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $telegram_chat_link;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    protected $organizer;

    /**
     * @var JointPurchaseProduct[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="JointPurchaseProduct", mappedBy="joint_purchase", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"title" = "ASC"})
     */
    protected $products;

    /**
     * @var JointPurchaseOrder[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="JointPurchaseOrder", mappedBy="joint_purchase", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"created_at" = "DESC"})
     */
    protected $orders;

    /**
     * JointPurchase constructor.
     */
    public function __construct()
    {
        $this->created_at   = new \DateTime();
        $this->final_date   = new \DateTime('+3 days');
        $this->orders       = new ArrayCollection();
        $this->products     = new ArrayCollection();
        $this->shipping_type = self::SHIPPING_TYPE_NONE;
        $this->status       = self::STATUS_DRAFT;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->title;
    }

    /**
     * @ORM\PreUpdate()
     */
    public function onUpdated()
    {
        $this->updated_at = new \DateTime();
    }

    /**
     * @return \DateTime
     */
    public function getFinalDate(): \DateTime
    {
        return $this->final_date;
    }

    /**
     * @param \DateTime $final_date
     *
     * @return $this
     */
    public function setFinalDate(\DateTime $final_date): self
    {
        $this->final_date = $final_date;

        return $this;
    }

    /**
     * @return User
     */
    public function getOrganizer(): User
    {
        return $this->organizer;
    }

    /**
     * @param User $organizer
     *
     * @return $this
     */
    public function setOrganizer(User $organizer): self
    {
        $this->organizer = $organizer;

        return $this;
    }

    /**
     * @return JointPurchaseProduct[]|ArrayCollection
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * @return int|null
     */
    public function getTransportationCostInPercent(): ?int
    {
        return $this->transportation_cost_in_percent;
    }

    /**
     * @param int|null $transportation_cost_in_percent
     *
     * @return $this
     */
    public function setTransportationCostInPercent(?int $transportation_cost_in_percent): self
    {
        $this->transportation_cost_in_percent = $transportation_cost_in_percent;

        return $this;
    }

    /**
     * @return JointPurchaseOrder[]|ArrayCollection
     */
    public function getOrders()
    {
        return $this->orders;
    }

    /**
     * @param JointPurchaseOrder[]|ArrayCollection $orders
     *
     * @return $this
     */
    public function setOrders($orders): self
    {
        $this->orders = $orders;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getTelegramChatLink(): ?string
    {
        return $this->telegram_chat_link;
    }

    /**
     * Получение ссылки для прямого вызова действия в телеграм
     *
     * @return string|null
     */
    public function getTelegramChatLinkAction(): ?string
    {
        if (!empty($this->telegram_chat_link)) {
            return "tg://join?invite=".str_replace('https://t.me/joinchat/', '', $this->telegram_chat_link);
        }

        return null;
    }

    /**
     * @param string|null $telegram_chat_link
     *
     * @return $this
     */
    public function setTelegramChatLink(?string $telegram_chat_link): self
    {
        if (!empty($telegram_chat_link) and stripos($telegram_chat_link, 'https://t.me/joinchat/') !== 0) {
            $telegram_chat_link = null;
        }

        $this->telegram_chat_link = $telegram_chat_link;

        return $this;
    }

    // Start STATUS block of setters and getters

    /**
     * @return array
     */
    static public function getStatusFormChoices(): array
    {
        return array_flip(self::$status_values);
    }

    /**
     * @return array
     */
    static public function getStatusValues(): array
    {
        return self::$status_values;
    }

    /**
     * @return bool
     */
    static public function isStatusExist($status): bool
    {
        if (isset(self::$status_values[$status])) {
            return true;
        }

        return false;
    }

    /**
     * @return string
     */
    public function getStatusAsText(): string
    {
        if (isset(self::$status_values[$this->status])) {
            return self::$status_values[$this->status];
        }

        return 'N/A';
    }

    /**
     * @return int
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * @param int $status
     *
     * @return $this
     */
    public function setStatus($status): self
    {
        $this->status = $status;

        return $this;
    }

    // __End STATUS block of setters and getters

    // Start "ShippingType" block of setters and getters

    /**
     * @return int
     *
     * @deprecated
     */
    public function getShippingType(): int
    {
        return $this->shipping_type;
    }

    /**
     * @param int $shipping_type
     *
     * @return $this
     *
     * @deprecated
     */
    public function setShippingType(int $shipping_type): self
    {
        $this->shipping_type = $shipping_type;

        return $this;
    }

    /**
     * @return array
     */
    static public function getShippingTypeFormChoices(): array
    {
        return array_flip(self::$shipping_type_values);
    }

    /**
     * @return array
     */
    static public function getShippingTypeValues(): array
    {
        return self::$shipping_type_values;
    }

    /**
     * @return bool
     */
    static public function isShippingTypeExist($shipping_type): bool
    {
        if (isset(self::$shipping_type_values[$shipping_type])) {
            return true;
        }

        return false;
    }

    /**
     * @return string
     */
    public function getShippingTypeAsText(): string
    {
        if (isset(self::$shipping_type_values[$this->shipping_type])) {
            return self::$shipping_type_values[$this->shipping_type];
        }

        return 'N/A';
    }

    // __End "ShippingType" block of setters and getters
}

src-vendor/JointPurchaseBundle/Entity/JointPurchaseProduct.php
<?php

declare(strict_types=1);

namespace Coop\JointPurchaseBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Позиции товаров в совместной закупке.
 *
 * @ORM\Entity()
 * @ORM\Table(name="joint_purchases_products",
 *      indexes={
 *          @ORM\Index(columns={"created_at"}),
 *          @ORM\Index(columns={"title"}),
 *      }
 * )
 *
 * @ORM\HasLifecycleCallbacks()
 */
class JointPurchaseProduct
{
    use ColumnTrait\Uuid;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\UpdatedAt;
    use ColumnTrait\TitleNotBlank;
    use ColumnTrait\Description;

    /**
     * ИД файла в медиалибе
     *
     * @var string|null
     *
     * @ORM\Column(type="string", length=36, nullable=true)
     */
    protected $image_id;

    /**
     * Необходимое минимальное кол-во
     *
     * @var int
     *
     * @ORM\Column(type="integer", nullable=false, options={"unsigned"=true})
     */
    protected $min_quantity;

    /**
     * Цена за еденицу товара
     *
     * @var int
     *
     * @ORM\Column(type="integer", nullable=false, options={"unsigned"=true})
     * @Assert\Range(min=1, minMessage="Цена должна быть больше 0")
     */
    protected $price;

    /**
     * @var JointPurchase
     *
     * @ORM\ManyToOne(targetEntity="JointPurchase", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $joint_purchase;

    /**
     * @var JointPurchaseOrderLine[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="JointPurchaseOrderLine", mappedBy="product", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"created_at" = "DESC"})
     */
    protected $order_lines;

    /**
     * JointPurchaseProduct constructor.
     */
    public function __construct(?JointPurchase $joint_purchase = null)
    {
        $this->created_at   = new \DateTime();
        $this->min_quantity = 10;
        $this->order_lines  = new ArrayCollection();
        $this->price        = 1;

        if ($joint_purchase) {
            $this->joint_purchase = $joint_purchase;
        }
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->getTitle();
    }

    /**
     * @ORM\PreUpdate()
     */
    public function onUpdated()
    {
        $this->updated_at = new \DateTime();
    }

    /**
     * @return int
     *
     * @deprecated
     */
    public function getCurrentQuantity(): int
    {
        $qty = 0;

        foreach ($this->order_lines as $orderLine) {
            $qty += $orderLine->getQuantity();
        }

        return $qty;
    }

    /**
     * @return string|null
     */
    public function getImageId(): ?string
    {
        return $this->image_id;
    }

    /**
     * @param string|null $image_id
     *
     * @return $this
     */
    public function setImageId(?string $image_id): self
    {
        $this->image_id = $image_id;

        return $this;
    }

    /**
     * @return int
     */
    public function getMinQuantity(): int
    {
        return $this->min_quantity;
    }

    /**
     * @param int $min_quantity
     *
     * @return $this
     */
    public function setMinQuantity(int $min_quantity): self
    {
        $this->min_quantity = $min_quantity;

        return $this;
    }

    /**
     * @return JointPurchase
     */
    public function getJointPurchase(): JointPurchase
    {
        return $this->joint_purchase;
    }

    /**
     * @param JointPurchase $joint_purchase
     *
     * @return $this
     */
    public function setJointPurchase(JointPurchase $joint_purchase): self
    {
        $this->joint_purchase = $joint_purchase;

        return $this;
    }

    /**
     * @return int
     */
    public function getPrice(): int
    {
        return $this->price;
    }

    /**
     * @param int $price
     *
     * @return $this
     */
    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return JointPurchaseOrderLine[]|ArrayCollection
     */
    public function getOrderLines()
    {
        return $this->order_lines;
    }

    /**
     * @param JointPurchaseOrderLine[]|ArrayCollection $order_lines
     *
     * @return $this
     */
    public function setOrderLines($order_lines): self
    {
        $this->order_lines = $order_lines;

        return $this;
    }
}

src-vendor/JointPurchaseBundle/Resources/views/_change_status_links.html.twig
{% if jp.status == 0 and jp.products|length > 0 %}
    <p>После оформления закупки, нужно сменить статус с "черновика", на "открытый". Тогда участники смогут видеть закупку в общем списке и подавать заявки за товары.</p>

    <a href="{{ path('jp_edit', {'id': jp.id, 'status': 'open'}) }}" class="btn btn-success" onclick="return confirm('Вы уверены, что хотите Открыть сбор заявок?')">
        Открыть сбор заявок
    </a>
{% elseif jp.status == 1 %}
    <p>Когда будет набрано необходимое кол-во заявок, нужно "закрыть" закупку, тогда пользователи больше не смогут подавать новые заявки на товары и изменять старые.</p>

    <a href="" class="btn btn-info">Закрыть сбор заявок</a>
{% elseif jp.status == 2 %}
    <a href="" class="btn">Заверщить</a>
{% endif %}

src-vendor/JointPurchaseBundle/Resources/views/_create_tg_chat_help.html.twig
<br>
<br>
<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Ссылка на чат в Телеграм</h4>

    <p>Для обсуждений конкретных закупок в общем чате, предлагается создавать групповой чат, куда участники будут самостоятельно входить по ссылке.
        При создании группового чата придётся сразу добавить хотябы ещё одного участника самостоятельно.
        Если вам некого добавить, то можно добавить чат-бота системы <code>@ncca_bot</code>
    </p>

    <p>Видео инструкции -
        <a href="https://www.youtube.com/results?search_query=%D0%BA%D0%B0%D0%BA+%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C+%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D0%BE%D0%B9+%D1%87%D0%B0%D1%82+%D0%B2+%D1%82%D0%B5%D0%BB%D0%B5%D0%B3%D1%80%D0%B0%D0%BC" target="_blank">
            как создать чат в телеграм
        </a>
    </p>

    <p>Для доступа к всяким настройкам нужно кникнуть по иконке "три вертикальных точки" или "три вертикальных черточки".</p>

    <p>Для редактирования настроек группы на телефоне, нужно кликнуть по её закголовку и там будет иконка "Карандашик"</p>

    <p>После создания группового чата в Телеграме, нужно зайти в <b>Управление группой</b>, нажать на пункт <b>Тип группы</b> и там нажать на <b>Создать ссылку-приглашение</b></p>

    <p>Ссылка будет иметь вид: <code>https://t.me/joinchat/[какой-то-код]</code>, именно эту строку и нужно вставить в поле формы.</p>

    <p>Также для удобства, рекомендуется включить <b>История чата для новых участников</b></p>

</div>

src-vendor/JointPurchaseBundle/Resources/views/_stats.html.twig
<br>
<br>
<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Информация по закупке</h4>

    <p><strong>Статус</strong>: {% include '@JointPurchase/_status.html.twig' %}</p>

    <p><strong>Организатор</strong>:
        {% if jp.organizer.telegramUsername %}
            <a href="tg://resolve?domain={{ jp.organizer.telegramUsername }}" title="Написать сообщение в Телеграм">{{ jp.organizer }}</a>
        {% else %}
            {{ jp.organizer }}
        {% endif %}
    </p>

    <p><strong>Ссылка на чат</strong>:
        {% if jp.telegramChatLink %}
            <a href="{{ jp.telegramChatLinkAction }}">присоединиться</a>
        {% else %}
            нет
        {% endif %}
    </p>

    <p><strong>Финальная дата:</strong> {{ jp.finalDate|format_date }}</p>

    <p><strong>Осталось дней:</strong> @todo</p>

    <p><strong>Транспортные расходы:</strong>
        {% if jp.transportationCostInPercent %}
            {{ jp.transportationCostInPercent }} %
        {% else %}
            нет
        {% endif %}
    </p>

    <p><strong>Позиций товаров:</strong> {{ jp.products|length }}</p>

    <p><strong>На сумму:</strong>
        {% set amount = 0 %}

        {% for product in jp.products %}
            {% set amount = amount + (product.price * product.minQuantity) %}
        {% endfor %}

        {{ amount }}
    </p>

    <p><strong>Собрана сумма:</strong>
        {% set collect = 0 %}

        {% for product in jp.products %}
            {% for orderLine in product.orderLines %}
                {% set collect = collect + (orderLine.quantity * product.price) %}
            {% endfor %}
        {% endfor %}

        {{ collect }}
    </p>

    <p><strong>Осталось собрать:</strong>
        {{ amount - collect }}
    </p>

</div>

{# Мой заказ #}
{% set my_order_amount = 0 %}

{% for product in jp.products %}
    {% for orderLine in product.orderLines %}
        {% if orderLine.order.user == app.user %}
            {% set my_order_amount = my_order_amount + (orderLine.quantity * product.price) %}
        {% endif %}
    {% endfor %}
{% endfor %}

{% if my_order_amount > 0 %}
<br>
<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Мой заказ в закупке</h4>
    <br>
    {% for product in jp.products %}
        {% for orderLine in product.orderLines %}
            {% if orderLine.order.user == app.user %}
                <p><strong>{{ product }}</strong><br> {{ orderLine.quantity }} x {{ product.price }} = {{ orderLine.quantity * product.price }}</p>
            {% endif %}
        {% endfor %}
    {% endfor %}

    <hr>
    <p><strong>Итого товаров на сумму:</strong> {{ my_order_amount }}</p>

    {% if jp.transportationCostInPercent %}
        <hr>
        <p>
        <b>Итоговая стоимость с транспортными расходами:</b>
            <br>
        {{ my_order_amount }} + {{ jp.transportationCostInPercent }} %
        = <b>{{ my_order_amount + (my_order_amount * jp.transportationCostInPercent / 100) | round }}</b> {# @todo make twig function #}
        </p>
    {% endif %}

</div>
{% endif %}

src-vendor/JointPurchaseBundle/Resources/views/_status.html.twig
{% if jp.status == 1 %}
    <span class="badge badge-success">{{ jp.statusAsText }}</span>
{% elseif jp.status == 3 %}
    <span class="badge badge-danger">{{ jp.statusAsText }}</span>
{% elseif jp.status == 2 %}
    <span class="badge badge-info">{{ jp.statusAsText }}</span>
{% else %}
    <span class="badge badge-light">{{ jp.statusAsText }}</span>
{% endif %}