src/Entity/ChatDialog.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ChatDialogRepository")
 * @ORM\Table(name="chats_dialogs",
 *      indexes={
 *          @ORM\Index(columns={"created_at"}),
 *          @ORM\Index(columns={"last_message_date"}),
 *          @ORM\Index(columns={"owner_id", "recipient_id"}),
 *      },
 * )
 */
class ChatDialog
{
    use ColumnTrait\Id;
    use ColumnTrait\CreatedAt;

    /**
     * @ORM\Column(type="datetime")
     */
    protected \DateTime $last_message_date;

    /**
     * @ORM\Column(type="text")
     */
    protected string $last_message_text;

    /**
     * @ORM\Column(type="integer", options={"default":0})
     */
    protected int $unread_owner_count = 0;

    /**
     * @ORM\Column(type="integer", options={"default":0})
     */
    protected int $unread_recipient_count = 0;

    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(nullable=false)
     */
    protected User $owner;

    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(nullable=false)
     */
    protected User $recipient;

    public function __construct(?User $owner = null, ?User $recipient = null)
    {
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();

        if ($owner) {
            $this->owner = $owner;
        }

        if ($recipient) {
            $this->recipient = $recipient;
        }
    }

    public function __toString(): string
    {
        return $this->last_message_text;
    }

    public function getAnnounce(): string
    {
        $text = str_replace(['<br>', '<br/>', '<br />'], ' ', $this->last_message_text);

        $a = strip_tags($text);

        if (mb_strlen($a, 'utf-8') > 120) {
            $dotted = '...';
        } else {
            $dotted = '';
        }

        return mb_substr($a, 0, 120, 'utf-8') . $dotted;
    }

    public function incrementUnreadOwnerCount(): self
    {
        $this->unread_owner_count++;

        return $this;
    }

    public function incrementUnreadRecipientCount(): self
    {
        $this->unread_recipient_count++;

        return $this;
    }

    public function getLastMessageText(): string
    {
        return $this->last_message_text;
    }

    public function setLastMessageText(string $last_message_text): self
    {
        $this->last_message_text = $last_message_text;
        $this->last_message_date = new \DateTime();

        return $this;
    }

    public function getLastMessageDate(): \DateTime
    {
        return $this->last_message_date;
    }

    public function setLastMessageDate(\DateTime $last_message_date): self
    {
        $this->last_message_date = $last_message_date;

        return $this;
    }

    public function getUnreadOwnerCount(): int
    {
        return $this->unread_owner_count;
    }

    public function setUnreadOwnerCount(int $unread_owner_count): self
    {
        $this->unread_owner_count = $unread_owner_count;

        return $this;
    }

    public function getUnreadRecipientCount(): int
    {
        return $this->unread_recipient_count;
    }

    public function setUnreadRecipientCount(int $unread_recipient_count): self
    {
        $this->unread_recipient_count = $unread_recipient_count;

        return $this;
    }

    public function getOwner(): User
    {
        return $this->owner;
    }

    public function setOwner(User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getRecipient(): User
    {
        return $this->recipient;
    }

    public function setRecipient(User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Controller/ImController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\ChatDialog;
use App\Entity\ChatMessage;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('im')]
class ImController extends AbstractController
{
    #[Route('/', name: 'im_index')]
    public function index(bool $isInternalMessengerEnable, EntityManagerInterface $em): Response
    {
        if (!$isInternalMessengerEnable) {
            return $this->redirectToRoute('homepage');
        }

        $dialogs = $em->getRepository(ChatDialog::class)->findBy(['owner' => $this->getUser()], ['last_message_date' => 'DESC']);

        return $this->render('im/index.html.twig', [
            'dialogs' => $dialogs,
        ]);
    }

    #[Route('/{id<\d+>}/', name: 'im_dialog')]
    public function dialog(int $id, bool $isInternalMessengerEnable, EntityManagerInterface $em, Request $request): Response
    {
        if (!$isInternalMessengerEnable) {
            return $this->redirectToRoute('homepage');
        }

        $dialog = $em->find(ChatDialog::class, $id);

        if (!$dialog or $dialog->getOwner() !== $this->getUser()) {
            return $this->redirectToRoute('im_index');
        }

        if ($request->isMethod('POST')) {
            $this->forward('App\Controller\ImController::sendMessage', $request->request->all());

            return $this->redirectToRoute('im_dialog', ['id' => $id]);
        }

        $em->getRepository(ChatMessage::class)->markAsReadForRecipient($dialog->getRecipient(), $dialog->getOwner());

        $dialog->setUnreadOwnerCount(0);

        $recipientDialog = $em->getRepository(ChatDialog::class)->findOneBy([
            'owner' => $dialog->getRecipient(),
            'recipient' => $this->getUser(),
        ]);

        if ($recipientDialog) {
            $recipientDialog->setUnreadRecipientCount(0);
        }

        $em->flush();

        $limit = 50;

        $messages = $em->getRepository(ChatMessage::class)->findForParticipants($dialog->getOwner(), $dialog->getRecipient(), $limit);

        return $this->render('im/dialog.html.twig', [
            'dialog' => $dialog,
            'messages' => array_reverse($messages),
            'limit' => $limit,
        ]);
    }

    #[Route('/{id<\d+>}/messages', name: 'im_dialog_messages')]
    public function dialogMessages(int $id, bool $isInternalMessengerEnable, EntityManagerInterface $em, Request $request): Response
    {
        if (!$isInternalMessengerEnable) {
            return $this->redirectToRoute('homepage');
        }

        $dialog = $em->find(ChatDialog::class, $id);

        if (!$dialog or $dialog->getOwner() !== $this->getUser()) {
            return $this->redirectToRoute('im_index');
        }

        $limit = (int) $request->query->get('limit', 50);
        $offset = (int) $request->query->get('offset', 0);

        $messages = $em->getRepository(ChatMessage::class)->findForParticipants($dialog->getOwner(), $dialog->getRecipient(), $limit, $offset);

        return $this->render('im/messages.html.twig', [
            'dialog' => $dialog,
            'messages' => array_reverse($messages),
        ]);
    }

    #[Route('/send_message', name: 'im_send_message', methods: ['POST'])]
    public function sendMessage(bool $isInternalMessengerEnable, EntityManagerInterface $em, Request $request): JsonResponse
    {
        if (!$isInternalMessengerEnable) {
            return $this->json([], 403);
        }

        // @todo запаковать в сервис

        $text = trim((string) $request->request->get('text'));

        if (!strlen($text)) {
            return $this->json(['message' => 'Нужно написать текст соообщения'], 400);
        }

        $recipient = $em->getRepository(User::class)->findOneBy(['id' => (string) $request->request->get('user_id')]);

        if (!$recipient) {
            return $this->json(['message' => 'Нет получателя'], 404);
        }

        $ownerDialog = $em->getRepository(ChatDialog::class)->findOneBy([
            'owner' => $this->getUser(),
            'recipient' => $recipient,
        ]);

        if (!$ownerDialog) {
            $ownerDialog = new ChatDialog($this->getUser(), $recipient);
            $em->persist($ownerDialog);
        }

        $recipientDialog = $em->getRepository(ChatDialog::class)->findOneBy([
            'owner' => $recipient,
            'recipient' => $this->getUser(),
        ]);

        if (!$recipientDialog) {
            $recipientDialog = new ChatDialog($recipient, $this->getUser());
            $em->persist($recipientDialog);
        }

        $chatMessage = new ChatMessage($this->getUser(), $recipient, $text);

        $ownerDialog
            ->setLastMessageText($text)
            ->incrementUnreadRecipientCount()
        ;

        $recipientDialog
            ->setLastMessageText($text)
            ->incrementUnreadOwnerCount()
        ;

        $em->persist($chatMessage);
        $em->flush();

        $this->addFlash('success', 'Сообщение отправлено'); // @todo remove

        return $this->json(['message' => 'ok']);
    }
}

templates/im/dialog.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ dialog.recipient }} - Диалог {% endblock %}

{% block css %}
    {{ parent() }}
    <style>
        #im_container {
            height: 87vh;
            display: flex;
            flex-direction: column;
        }
        #im_messages {
            flex: auto;
            overflow: auto;
            bottom: 0;
        }
        #im_container > form {
            flex-shrink: 0;
        }
        #im_text {
            min-height: 40px;
        }
        .im_msg {
            display: inline-block;
            clear: both;
        }
        .im_msg_date, form span {
            float: right;
            opacity: 0.5;
            margin-left: 6px;
            margin-top: 5px;
        }
        .im_msg_text {
            border-radius: 9px;
            padding: 7px 10px;
        }
        .im_msg_own .im_msg_text {
            background-color: rgba(0,81,159,0.99);
        }
        .im_msg_own {
            color: white;
            margin: 8px 0px 2px auto;
            padding-left: 50px;
            float: right;
        }
        .im_msg_recipient {
            float: left;
            margin: 8px auto 2px 0;
            padding-right: 50px;
        }
    </style>
{% endblock %}

{% block content %}
    <a href="{{ path('im_index') }}" style="float: right; margin-top: 10px;"><< все диалоги</a>

    <h2>Диалог - {{ dialog.recipient }}</h2>

    <div id="im_container">
        <div id="im_temp"></div>

        <div id="im_messages" onScroll="handleOnScroll();">
            {% include 'im/messages.html.twig' with {'messages': messages} %}
        </div>

        <form id="im_send_msg_form" method="post">
            <input type="hidden" name="user_id" value="{{ dialog.recipient.id }}">
            <textarea class="form-control" id="im_text" name="text" rows="2" autofocus placeholder="Написать сообщение..."></textarea>
            <button type="submit" class="btn btn-success" id="im_send_msg_form_submit">Отправить</button>
            <span>отправить: Ctrl+Enter</span>
        </form>
    </div>
{% endblock %}

{#{% block theme_toggler '' %}#}

{% block js %}
    {{ parent() }}
    <script>
        var offset = 0;

        $(document).ready(function() {
            document.getElementById('im_messages').scrollTop = 9999999;

            $('#im_text').keydown(function (e) {
                if (e.ctrlKey && e.keyCode === 13) {
                    $('#im_send_msg_form').submit()
                }
            });
        });

        function handleOnScroll() {
            var div = document.getElementById('im_messages');

            if (div.scrollTop === 0) {
                offset = offset + {{ limit }}

                $.get('{{ path('im_dialog_messages', {'id': dialog.id}) }}', {
                    limit: {{ limit }},
                    offset: offset
                }).done(function (data) {
                    if (data.length) {
                        $d = $('#im_temp').prepend(data)
                        h = $d.outerHeight();

                        $('#im_messages').prepend($('#im_temp').html())
                        $('#im_temp').empty()

                        document.getElementById('im_messages').scrollTop = h;

                        h = 0;
                    }
                });
            }

            // console.log(div.scrollTop)
        };
    </script>
{% endblock js %}

templates/im/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Диалоги {% endblock %}

{% block css %}
    {{ parent() }}
    <style>
        .clickable-row tr {
            cursor: pointer;
        }
    </style>
{% endblock %}

{% block content %}
    <h2>Диалоги</h2>

    <table class="table table-bordered table-hover clickable-row">
        {% for dialog in dialogs %}
        <tr data-href="{{ path('im_dialog', {'id': dialog.id}) }}">
            <td nowrap>
                {{ dialog.recipient }}

                {% if dialog.unreadOwnerCount %}
                    <span class="badge badge-pill badge-primary">{{ dialog.unreadOwnerCount }}</span>
                {% elseif dialog.unreadRecipientCount %}
                    <span class="badge badge-pill badge-secondary">{{ dialog.unreadRecipientCount }}</span>
                {% endif %}
            </td>
            <td style="width: 100%;">{{ dialog.announce|raw }}</td>
            <td nowrap>{{ dialog.lastMessageDate|app_date }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

{% block js %}
    {{ parent() }}
    <script>
        $(document).ready( function() {
            $(".clickable-row tr").click(function() {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock js %}

templates/im/messages.html.twig
{% for message in messages %}
{% if message.author == app.user %}
    {% set im_msg_type = 'im_msg_own' %}
{% else %}
    {% set im_msg_type = 'im_msg_recipient' %}
{% endif %}

<div class="im_msg {{ im_msg_type }}">
    <div class="im_msg_text">
        {{ message|nl2br|raw }}
        <span class="im_msg_date">
            {{ message.createdAt|app_date }}
        </span>
    </div>
</div>
{% endfor %}