src/Entity/Deal.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Doctrine\StatusTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;

/**
 * Сделки
 *
 * @ORM\Entity(repositoryClass="App\Repository\DealRepository")
 * @ORM\Table(name="deals",
 *      indexes={
 *          @ORM\Index(columns={"amount_cost"}),
 *          @ORM\Index(columns={"created_at"}),
 *          @ORM\Index(columns={"updated_at"}),
 *          @ORM\Index(columns={"status"}),
 *          @ORM\Index(columns={"type"}),
 *      }
 * )
 * @ORM\HasLifecycleCallbacks()
 */
class Deal
{
    use ColumnTrait\Uuid;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\UpdatedAt;
    use ColumnTrait\Comment;

    use StatusTrait;

    const TYPE_EXTERNAL = 0;
    const TYPE_INNER    = 1;

    const STATUS_NEW                    = 0;
    const STATUS_VIEW                   = 1;
    const STATUS_ACCEPTED               = 2;
    const STATUS_ACCEPTED_EXTERNAL      = 3;
    const STATUS_COMPLETE               = 4;
    const STATUS_COMPLETE_OUTSIDE       = 5;
    const STATUS_CANCEL_BY_BUYER        = 6;
    const STATUS_CANCEL_BY_SELLER       = 7;
    static protected $status_values = [
        self::STATUS_NEW                => 'Новая',
        self::STATUS_VIEW               => 'Просмотрено',
        self::STATUS_ACCEPTED           => 'Принято',
        self::STATUS_ACCEPTED_EXTERNAL  => 'Принято для совершения вне системы',
        self::STATUS_COMPLETE           => 'Завершено',
        self::STATUS_COMPLETE_OUTSIDE   => 'Завершено вне системы',
        self::STATUS_CANCEL_BY_BUYER    => 'Отменено покупателем',
        self::STATUS_CANCEL_BY_SELLER   => 'Отменено продавцом',
    ];

    /**
     * @ORM\Column(type="smallint", nullable=false, options={"default":1})
     */
    protected int $type;

    /**
     * Стоимость предложения на момент создания сделки.
     *
     * @ORM\Column(type="integer", nullable=false, options={"unsigned"=true})
     */
    protected int $cost;

    /**
     * Фактическая стоимость - до которой договорились участники.
     *
     * @ORM\Column(type="integer", nullable=false, options={"unsigned"=true})
     */
    protected int $actual_cost;

    /**
     * Общая стоимость - кол-во помноженное на фактическую стоимость.
     *
     * @ORM\Column(type="integer", nullable=false, options={"unsigned"=true})
     */
    protected int $amount_cost;

    /**
     * Кол-во
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected ?int $quantity;

    /**
     * Дата просмотра
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected ?\DateTimeInterface $viewed_at;

    /**
     * @var Offer
     *
     * @ORM\ManyToOne(targetEntity="Offer")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $offer;

    /**
     * Продавец
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(nullable=false)
     */
    protected User $seller;

    /**
     * Покупатель
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(nullable=false)
     */
    protected User $buyer;

    /**
     * @var Transaction[]|Collection
     *
     * @ORM\OneToMany(targetEntity="Transaction", mappedBy="deal", fetch="EXTRA_LAZY")
     */
    protected Collection $transactions;

    public function __construct()
    {
        $this->created_at   = new \DateTime();
        $this->status       = self::STATUS_NEW;
        $this->transactions = new ArrayCollection();
        $this->type         = self::TYPE_INNER;
    }

    public function getTypeText(): string
    {
        switch ($this->type) {
            case self::TYPE_EXTERNAL:
                return 'Внешняя';
            case self::TYPE_INNER:
                return 'Внутренняя';
            default:
                throw new \ErrorException('Не допустимый тип сделки: ' . $this->type);
        }
    }

    /**
     * @ORM\PreUpdate()
     */
    public function onUpdated(): void
    {
        $this->updated_at = new \DateTime();
    }

    public function getCost(): int
    {
        return $this->cost;
    }

    public function setCost(int $cost): Deal
    {
        $this->cost = $cost;

        return $this;
    }

    public function getActualCost(): int
    {
        return $this->actual_cost;
    }

    public function setActualCost($actual_cost): self
    {
        $this->actual_cost = $actual_cost;

        return $this;
    }

    public function getAmountCost(): int
    {
        return $this->amount_cost;
    }

    public function setAmountCost(int $amount_cost): self
    {
        $this->amount_cost = $amount_cost;

        return $this;
    }

    public function getQuantity(): int
    {
        return (int) $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getViewedAt(): ?\DateTime
    {
        return $this->viewed_at;
    }

    public function setViewedAt($viewed_at): self
    {
        $this->viewed_at = $viewed_at;

        return $this;
    }

    public function getOffer(): Offer
    {
        return $this->offer;
    }

    public function setOffer(Offer $offer): self
    {
        $this->offer = $offer;

        return $this;
    }

    public function getBuyer(): User
    {
        return $this->buyer;
    }

    public function setBuyer(User $buyer): self
    {
        $this->buyer = $buyer;

        return $this;
    }

    /**
     * @return Transaction[]|Collection
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    /**
     * @param Transaction[]|Collection $transactions
     */
    public function setTransactions($transactions): self
    {
        $this->transactions = $transactions;

        return $this;
    }

    public function getSeller(): User
    {
        return $this->seller;
    }

    public function setSeller(User $seller): self
    {
        $this->seller = $seller;

        return $this;
    }

    public function getType(): int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }
}

src/Entity/Offer.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Doctrine\StatusTrait;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use Smart\CoreBundle\Doctrine\ColumnTrait\IsEnabled;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Предложение (товар или услуга), они же "Объявления"
 *
 * @ORM\Entity(repositoryClass="App\Repository\OfferRepository")
 * @ORM\Table(name="offers",
 *      indexes={
 *          @ORM\Index(columns={"created_at"}),
 *          @ORM\Index(columns={"is_enabled"}),
 *          @ORM\Index(columns={"price"}),
 *          @ORM\Index(columns={"status"}),
 *          @ORM\Index(columns={"title"}),
 *      },
 *      uniqueConstraints={
 *          @ORM\UniqueConstraint(columns={"user_id", "title"}),
 *      }
 * )
 *
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"user", "title"}, message="Title must be unique")
 */
class Offer
{
    use ColumnTrait\Uuid;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\UpdatedAt;
    use ColumnTrait\TitleNotBlank;
    use ColumnTrait\Description;
    use ColumnTrait\User;

    use StatusTrait;

    const MEASURE_NONE  = 0;
    const MEASURE_PIECE = 1;
    const MEASURE_GRAM  = 2;
    const MEASURE_KG    = 3;
    const MEASURE_LITRE = 4;
    static protected $measure_values = [
        self::MEASURE_NONE  => 'нет',
        self::MEASURE_PIECE => 'шт',
        self::MEASURE_GRAM  => 'гр',
        self::MEASURE_KG    => 'кг',
        self::MEASURE_LITRE => 'л',
    ];

    const STATUS_NOT_AVAILABLE  = 0;
    const STATUS_AVAILABLE      = 1;
    const STATUS_RESERVE        = 2;
    const STATUS_ON_DEMAND      = 3;
    static protected $status_values = [
        self::STATUS_AVAILABLE      => 'Есть в наличии',
        self::STATUS_ON_DEMAND      => 'Под заказ',
        self::STATUS_RESERVE        => 'Резерв',
        self::STATUS_NOT_AVAILABLE  => 'Нет в наличии', // не участвует в эмиссии
    ];

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default":1})
     */
    protected bool $is_enabled;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected int $price;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\Length(max = 160, allowEmptyString=false)
     */
    protected ?string $short_description;

    /**
     * Еденицы измерения
     *
     * @ORM\Column(type="smallint", nullable=false)
     */
    protected int $measure;

    /**
     * Количество
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected ?int $quantity;

    /**
     * Кол-во в резерве
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected ?int $quantity_reserved = null;

    /**
     * ИД файла в медиалибе
     *
     * @ORM\Column(type="string", length=36, nullable=true)
     */
    protected ?string $image_id = null;

    /**
     * @var Category
     *
     * @ORM\ManyToOne(targetEntity="Category")
     * @ORM\JoinColumn(nullable=false)
     */
    protected Category $category;

    /**
     * @ORM\ManyToOne(targetEntity="City")
     */
    protected ?City $city = null;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->is_enabled = true;
        $this->measure    = self::MEASURE_NONE;
        $this->status     = self::STATUS_AVAILABLE;
    }

    public function __toString(): string
    {
        return $this->title;
    }

    public function getQuantityAvailable(): ?int
    {
        return $this->quantity - $this->quantity_reserved;
    }

    /**
     * @ORM\PreFlush()
     */
    public function preFlush(): void
    {
        if ($this->getMeasure() == self::MEASURE_NONE) {
            $this->setQuantity(null);
            $this->setQuantityReserved(null);
        }
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getPriceTotal(): ?int
    {
        if (empty($this->quantity)) {
            return $this->price;
        }

        return $this->price * $this->quantity;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function isStatusAccessToOrder(): bool
    {
        if ($this->status == self::STATUS_AVAILABLE or $this->status == self::STATUS_ON_DEMAND) {
            return true;
        }

        return false;
    }

    public function getMeasure(): int
    {
        return $this->measure;
    }

    public function getMeasureAsText(): string
    {
        return self::$measure_values[$this->measure];
    }

    public function setMeasure(int $measure): self
    {
        $this->measure = $measure;

        return $this;
    }

    static public function getMeasureValues(): array
    {
        return self::$measure_values;
    }

    static public function getMeasureFormChoices(): array
    {
        return array_flip(self::$measure_values);
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getQuantityReserved(): ?int
    {
        return $this->quantity_reserved;
    }

    public function setQuantityReserved(?int $quantity_reserved): self
    {
        $this->quantity_reserved = $quantity_reserved;

        return $this;
    }

    public function getImageId(): ?string
    {
        return $this->image_id;
    }

    public function setImageId(?string $image_id): self
    {
        $this->image_id = $image_id;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function setIsEnabled(bool $is_enabled): self
    {
        $this->is_enabled = $is_enabled;

        return $this;
    }

    public function getIsEnabled(): bool
    {
        return $this->is_enabled;
    }

    public function getIsEnabledAsText(): string
    {
        return $this->is_enabled ? 'Yes' : 'No';
    }

    public function isEnabled(): bool
    {
        return $this->is_enabled;
    }

    public function isDisabled(): bool
    {
        return !$this->is_enabled;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }
}

templates/deal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Мои сделки{% endblock %}

{% block content %}
    <h1>Мои сделки</h1>

    <ul class="nav nav-pills">
        <li {% if show == 'new' %}class="active"{% endif %}>
            <a href="{{ path('deals', {'tab': 'new'}) }}">
                Новые

                {% set deals_count_new = app_deals_count_new_by_user(app.user) %}
                {% if deals_count_new %}
                    <span class="badge badge-primary">{{ deals_count_new }}</span>
                {% endif %}
            </a>
        </li>

        <li {% if show == 'active' %}class="active"{% endif %}>
            <a href="{{ path('deals', {'tab': 'active'}) }}">
                Активные

                {% set deals_count_active = app_deals_count_active_by_user(app.user) %}
                {% if deals_count_active %}
                    <span class="badge badge-primary">{{ deals_count_active }}</span>
                {% endif %}
            </a>
        </li>

        <li {% if show == 'in' %}class="active"{% endif %}>
            <a href="{{ path('deals', {'tab': 'in'}) }}">
                Входящие

                {% set deals_count_new_incoming = app_deals_count_new_incoming_by_user(app.user) %}
                {% if deals_count_new_incoming %}
                    <span class="badge badge-danger">{{ deals_count_new_incoming }}</span>
                {% else %}
                    {% set deals_count_incoming = app_deals_count_incoming_by_user(app.user) %}

                    {% if deals_count_incoming %}
                        <span class="badge badge-primary">{{ deals_count_incoming }}</span>
                    {% endif %}
                {% endif %}
            </a>
        </li>

        <li {% if show == 'out' %}class="active"{% endif %}>
            <a href="{{ path('deals', {'tab': 'out'}) }}">
                Исходящие

                {% set deals_count_outgoing = app_deals_count_outgoing_by_user(app.user) %}
                {% if deals_count_outgoing %}
                    <span class="badge badge-primary">{{ deals_count_outgoing }}</span>
                {% endif %}
            </a>
        </li>

        <li {% if show == 'complete' %}class="active"{% endif %}><a href="{{ path('deals', {'tab': 'complete'}) }}">Завершенные</a></li>

        <li {% if show == 'canceled' %}class="active"{% endif %}><a href="{{ path('deals', {'tab': 'canceled'}) }}">Отменённые</a></li>

        <li {% if show == 'all' %}class="active"{% endif %}><a href="{{ path('deals', {'tab': 'all'}) }}">Все</a></li>
    </ul>

    <p>Всего: <b>{{ pagerfanta|length }}</b>
        {#{% if pagerfanta.haveToPaginate %} Текущая страница: <b>{{ pagerfanta.currentPage }}</b> Записей на страницу: <b>{{ pagerfanta.maxPerPage }}</b>{% endif %}#}
    </p>

    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            {% if show == 'active' or show == 'complete' or show == 'canceled' or show == 'all' %}<th>Тип</th>{% endif %}
            <th>Предложение</th>
            <th>Сумма</th>
            <th>Участник</th>
            <th>Тип взаимозачёта</th>
            <th>Статус</th>
            <th>Дата создания</th>
            <th>Дата обновления</th>
        </tr>
        </thead>
        <tbody>
        {% for deal in pagerfanta %}
            <tr {% if deal.viewedAt is null %} class="table-info" title="Не просмотрено" {% endif %}>
                {% if show == 'active' or show == 'complete' or show == 'canceled' or show == 'all' %}
                    <td>
                        {% if deal.seller == app.user %}
                            Входящие
                        {% elseif deal.buyer == app.user %}
                            Исходящие
                        {% endif %}
                    </td>
                {% endif %}
                <td>
                    <a href="{{ path('deal_show', {'id': deal.id}) }}">{{ deal.offer.title }}</a>
                    {{ deal.cost }}{{ app_currency() }} x {{ deal.quantity }}
                </td>
                <td>{{ deal.amountCost }}{{ app_currency() }}</td>
                <td>
                    {% if deal.seller == app.user %}
                        <a href="{{ path('user_show', {'id': deal.buyer.id}) }}">{{ deal.buyer }}</a>
                    {% elseif deal.buyer == app.user %}
                        <a href="{{ path('user_show', {'id': deal.seller.id}) }}">{{ deal.seller }}</a>
                    {% endif %}
                </td>
                <td>{{ deal.typeText }}</td>
                <td>{{ deal.statusAsText }}
                    {% if deal.status == 1 %}
                        <br>{{ deal.viewedAt|format_datetime }}
                    {% endif %}
                </td>
                <td>{{ deal.createdAt|format_datetime }}</td>
                <td>
                    {% if deal.updatedAt is not empty %}
                        {{ deal.updatedAt|format_datetime }}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {#
    {% if pagerfanta.haveToPaginate %}
        {{ pagerfanta(pagerfanta, 'twitter_bootstrap_translated', {'css_container_class': 'pagination pagination-centered'}) }}
    {% endif %}
    #}
{% endblock %}

templates/deal/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Просмотр сделки{% endblock %}

{% block content %}
    {% set offer = deal.offer %}
    {% set show = false %}

    <h1>Мои сделки</h1>

    <ul class="nav nav-pills">
        <li {% if show == 'active' %}class="active"{% endif %}><a href="{{ path('deals', {'tab': 'active'}) }}">Активные</a></li>
        <li {% if show == 'in' %}class="active"{% endif %}><a href="{{ path('deals', {'tab': 'in'}) }}">Входящие</a></li>
        <li {% if show == 'out' %}class="active"{% endif %}><a href="{{ path('deals', {'tab': 'out'}) }}">Исходящие</a></li>
        <li {% if show == 'complete' %}class="active"{% endif %}><a href="{{ path('deals', {'tab': 'complete'}) }}">Завершенные</a></li>
        <li {% if show == 'canceled' %}class="active"{% endif %}><a href="{{ path('deals', {'tab': 'canceled'}) }}">Отменённые</a></li>
        <li {% if show == 'all' %}class="active"{% endif %}><a href="{{ path('deals', {'tab': 'all'}) }}">Все</a></li>
    </ul>

    <h2>Просмотр сделки</h2>

<div class="row">
    <div class="col-md-8">
        <div class="myform">
    <h3>
        {% if deal.seller == app.user %}
            Входящий запрос от <a href="{{ path('user_show', {'id': deal.buyer.id}) }}">{{ deal.buyer }}</a>
        {% elseif deal.buyer == app.user %}
            Вы запросили у <a href="{{ path('user_show', {'id': deal.seller.id}) }}">{{ deal.seller }}</a>
        {% endif %}
    </h3>

    {% if deal.seller == app.user and deal.buyer.telegramUsername %}
        <p>
            <a href="tg://resolve?domain={{ deal.buyer.telegramUsername }}">
                Написать сообщение

                <span title="Написать сообщение в Телеграм" style="float: left; color: Dodgerblue; padding-right: 8px;">
                        <i class="fab fa-telegram-plane"></i>
                </span>
            </a>
        </p>
    {% endif %}

    {% if deal.buyer == app.user and deal.seller.telegramUsername %}
        <p>
            <a href="tg://resolve?domain={{ deal.seller.telegramUsername }}">
                Написать сообщение

                <span title="Написать сообщение в Телеграм" style="float: left; color: Dodgerblue; padding-right: 8px;">
                        <i class="fab fa-telegram-plane"></i>
                </span>
            </a>
        </p>
    {% endif %}

    <p>Дата: {{ deal.createdAt|format_datetime }}</p>

    <p>Предложение: <a href="{{ path('offer_show', {'id': offer.id}) }}">{{ offer }}</a></p>

    <p>Количество: {{ deal.quantity }} <i>{{ offer.quantity ? offer.measureAsText : '' }}</i></p>

    <p>Стоимость: {{ deal.offer.price }}{{ app_currency() }}
        {% if deal.offer.quantity > 0 %}
            за <i>{{ deal.offer.measureAsText }}</i>
        {% endif %}
    </p>

    <p>Итоговая сумма: {{ deal.amountCost }}{{ app_currency() }}</p>

    <p>Статус:
        {{ deal.statusAsText }}
        {% if deal.status == constant('App\\Entity\\Deal::STATUS_VIEW') %}
            {{ deal.viewedAt|format_datetime }}
        {% endif %}
    </p>

    {% if deal.comment is not empty %}
        <p>Комментарий: {{ deal.comment }}</p>
    {% endif %}

    {% if deal.updatedAt is not empty %}
        <p>Дата последнего изменения: {{ deal.updatedAt|format_datetime }}</p>
    {% endif %}

    <p>Тип взаимозачёта:
        <b>{{ deal.typeText }}</b>
    </p>

    {% if deal.status == constant('App\\Entity\\Deal::STATUS_NEW') or deal.status == constant('App\\Entity\\Deal::STATUS_VIEW') %}
        <br>
        {% if deal.seller.id == app.user.id %}
            <p>
                <a href="{{ path('deal_show', {'id': deal.id, 'action': 'accept'}) }}" class="btn btn-success" onclick="return confirm('Вы уверены, что хотите принять заявку?')">
                    {% if deal.type == constant('App\\Entity\\Deal::TYPE_INNER') %}
                        Принять для внутреннего бартерного обмена
                    {% else %}
                        Принять для личной договорённости *
                    {% endif %}
                </a>

                <a href="{{ path('deal_show', {'id': deal.id, 'action': 'cancel'}) }}" class="btn btn-danger" onclick="return confirm('Вы уверены, что хотите отменить заявку?')">Отклонить</a>
            </p>

            {% if deal.type == constant('App\\Entity\\Deal::TYPE_EXTERNAL') %}
                <br>
                <p>* - <i>в данном случае участники самостоятельно решают на каких условиях совершить обмен по данному предложению и стоимость сделки не затрагивает балансы участников в системе.</i></p>
            {% endif %}

        {% elseif deal.buyer.id == app.user.id %}
            <p>
                <a href="{{ path('deal_show', {'id': deal.id, 'action': 'cancel'}) }}" class="btn btn-danger" onclick="return confirm('Вы уверены, что хотите отменить заявку?')">
                    Отменить, если вы передумали
                </a>
            </p>
        {% endif %}
    {% endif %}

    {% if deal.status == constant('App\\Entity\\Deal::STATUS_ACCEPTED') or deal.status == constant('App\\Entity\\Deal::STATUS_ACCEPTED_EXTERNAL') %}
        <br>
        {% if deal.buyer.id == app.user.id %}
            <div class="alert alert-info" role="alert">
                После того, как вы произведёте обмен, нужно будет завершить сделку.
            </div>

            <p>
                <a href="{{ path('deal_show', {'id': deal.id, 'action': 'complete'}) }}" class="btn btn-success" onclick="return confirm('Вы уверены, что хотите завершить сделку?')">Завершить</a>
            </p>

            <br>
            {#<p>* - <i>в данном случае участники самостоятельно решают на каких условиях совершить обмен по данному предложения и стоимость сделки не затрагивает балансы участников в системе.</i></p>#}
        {% elseif deal.seller.id == app.user.id %}
            <div class="alert alert-info" role="alert">
                После того, как вы произведёте обмен, нужно будет завершить сделку, для начисления баллов.
            </div>

            <p>
                {#<a href="{{ path('site.deal.show', {'id': deal.id, 'action': 'cancel'}) }}" class="btn btn-default" onclick="return confirm('Вы уверены, что хотите отменить заявку?')">Отменить, если вы передумали</a>#}
            </p>
        {% endif %}
    {% endif %}
        </div>

{#        <a href="{{ path('deals', {'tab': 'in'}) }}"><< назад к списку входящих запросов</a>#}
    </div>

    <div class="col-md-4">
        <div class="alert alert-warning" role="alert">
            <h5>Предложение</h5>
            <p>Категория <a href="#">{{ offer.category }}</a></p>
            <h4>{{ offer }}</h4>
            <img src="{{ path('image', {'filter': 'offers_list_thumbnail', 'id': offer.imageId ?:0 }) }}" class="img-fluid">
            <h4>
                <span class="badge badge-secondary">
                {% if offer.price == 0 %}
                    Договорная
                {% else %}
                    {{ offer.price|number_format(0, ' ', ' ') }}{{ app_currency() }}
                {% endif %}
                </span>

                {% include 'offer/_status.html.twig' %}
            </h4>

            <p>{{ offer.shortDescription }}</p>

            <p>{{ offer.createdAt|format_datetime }}</p>
        </div>
    </div>
</div>

{% endblock %}