src/Entity/Offer.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Doctrine\StatusTrait;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use Smart\CoreBundle\Doctrine\ColumnTrait\IsEnabled;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Предложение (товар или услуга), они же "Объявления"
 *
 * @ORM\Entity(repositoryClass="App\Repository\OfferRepository")
 * @ORM\Table(name="offers",
 *      indexes={
 *          @ORM\Index(columns={"created_at"}),
 *          @ORM\Index(columns={"is_enabled"}),
 *          @ORM\Index(columns={"price"}),
 *          @ORM\Index(columns={"status"}),
 *          @ORM\Index(columns={"title"}),
 *      },
 *      uniqueConstraints={
 *          @ORM\UniqueConstraint(columns={"user_id", "title"}),
 *      }
 * )
 *
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"user", "title"}, message="Title must be unique")
 */
class Offer
{
    use ColumnTrait\Uuid;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\UpdatedAt;
    use ColumnTrait\TitleNotBlank;
    use ColumnTrait\Description;
    use ColumnTrait\User;

    use StatusTrait;

    const MEASURE_NONE  = 0;
    const MEASURE_PIECE = 1;
    const MEASURE_GRAM  = 2;
    const MEASURE_KG    = 3;
    const MEASURE_LITRE = 4;
    static protected $measure_values = [
        self::MEASURE_NONE  => 'нет',
        self::MEASURE_PIECE => 'шт',
        self::MEASURE_GRAM  => 'гр',
        self::MEASURE_KG    => 'кг',
        self::MEASURE_LITRE => 'л',
    ];

    const STATUS_NOT_AVAILABLE  = 0;
    const STATUS_AVAILABLE      = 1;
    const STATUS_RESERVE        = 2;
    const STATUS_ON_DEMAND      = 3;
    static protected $status_values = [
        self::STATUS_AVAILABLE      => 'Есть в наличии',
        self::STATUS_ON_DEMAND      => 'Под заказ',
        self::STATUS_RESERVE        => 'Резерв',
        self::STATUS_NOT_AVAILABLE  => 'Нет в наличии', // не участвует в эмиссии
    ];

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default":1})
     */
    protected bool $is_enabled;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected int $price;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\Length(max = 160, allowEmptyString=false)
     */
    protected ?string $short_description;

    /**
     * Еденицы измерения
     *
     * @ORM\Column(type="smallint", nullable=false)
     */
    protected int $measure;

    /**
     * Количество
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected ?int $quantity;

    /**
     * Кол-во в резерве
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected ?int $quantity_reserved = null;

    /**
     * ИД файла в медиалибе
     *
     * @ORM\Column(type="string", length=36, nullable=true)
     */
    protected ?string $image_id = null;

    /**
     * @var Category
     *
     * @ORM\ManyToOne(targetEntity="Category")
     * @ORM\JoinColumn(nullable=false)
     */
    protected Category $category;

    /**
     * @ORM\ManyToOne(targetEntity="City")
     */
    protected ?City $city = null;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->is_enabled = true;
        $this->measure    = self::MEASURE_NONE;
        $this->status     = self::STATUS_AVAILABLE;
    }

    public function __toString(): string
    {
        return $this->title;
    }

    public function getQuantityAvailable(): ?int
    {
        return $this->quantity - $this->quantity_reserved;
    }

    /**
     * @ORM\PreFlush()
     */
    public function preFlush(): void
    {
        if ($this->getMeasure() == self::MEASURE_NONE) {
            $this->setQuantity(null);
            $this->setQuantityReserved(null);
        }
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getPriceTotal(): ?int
    {
        if (empty($this->quantity)) {
            return $this->price;
        }

        return $this->price * $this->quantity;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function isStatusAccessToOrder(): bool
    {
        if ($this->status == self::STATUS_AVAILABLE or $this->status == self::STATUS_ON_DEMAND) {
            return true;
        }

        return false;
    }

    public function getMeasure(): int
    {
        return $this->measure;
    }

    public function getMeasureAsText(): string
    {
        return self::$measure_values[$this->measure];
    }

    public function setMeasure(int $measure): self
    {
        $this->measure = $measure;

        return $this;
    }

    static public function getMeasureValues(): array
    {
        return self::$measure_values;
    }

    static public function getMeasureFormChoices(): array
    {
        return array_flip(self::$measure_values);
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getQuantityReserved(): ?int
    {
        return $this->quantity_reserved;
    }

    public function setQuantityReserved(?int $quantity_reserved): self
    {
        $this->quantity_reserved = $quantity_reserved;

        return $this;
    }

    public function getImageId(): ?string
    {
        return $this->image_id;
    }

    public function setImageId(?string $image_id): self
    {
        $this->image_id = $image_id;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function setIsEnabled(bool $is_enabled): self
    {
        $this->is_enabled = $is_enabled;

        return $this;
    }

    public function getIsEnabled(): bool
    {
        return $this->is_enabled;
    }

    public function getIsEnabledAsText(): string
    {
        return $this->is_enabled ? 'Yes' : 'No';
    }

    public function isEnabled(): bool
    {
        return $this->is_enabled;
    }

    public function isDisabled(): bool
    {
        return !$this->is_enabled;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }
}

src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Model\UserModel;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table("users",
 *      indexes={
 *          @ORM\Index(columns={"created_at"}),
 *          @ORM\Index(columns={"confirmation_token"}),
 *          @ORM\Index(columns={"firstname"}),
 *          @ORM\Index(columns={"lastname"}),
 *          @ORM\Index(columns={"last_login"}),
 *          @ORM\Index(columns={"level"}),
 *          @ORM\Index(columns={"is_alcohol"}),
 *          @ORM\Index(columns={"is_enabled"}),
 *          @ORM\Index(columns={"is_smoking"}),
 *          @ORM\Index(columns={"is_meat_consumption"}),
 *          @ORM\Index(columns={"sex"}),
 *      },
 * )
 *
 * @Gedmo\Tree(type="closure")
 * @Gedmo\TreeClosure(class="UserClosure")
 *
 * @UniqueEntity(
 *     fields="username_canonical",
 *     errorPath="username",
 *     message="Username is already exists"
 * )
 */
class User extends UserModel
{
    use ColumnTrait\Description;

    const SEX_NA     = 0;
    const SEX_MALE   = 1;
    const SEX_FEMALE = 2;
    static protected $sex_values = [
        self::SEX_NA     => 'Не указан',
        self::SEX_MALE   => 'Мужской',
        self::SEX_FEMALE => 'Женский',
    ];

    /**
     * This parameter is optional for the closure strategy
     *
     * @ORM\Column(type="integer", nullable=false, options={"default":1})
     * @Gedmo\TreeLevel
     */
    protected int $level;

    /**
     * Пол
     *
     * @ORM\Column(type="smallint", nullable=false, options={"unsigned"=true, "default":0})
     * @Assert\NotNull(message="This value is not valid.")
     */
    protected int $sex;

    /**
     * Курение
     *
     * @ORM\Column(type="boolean", nullable=true)
     * Assert\NotNull(message="This value is not valid.")
     */
    protected ?bool $is_smoking;

    /**
     * Алкаголь
     *
     * @ORM\Column(type="boolean", nullable=true)
     * Assert\NotNull(message="This value is not valid.")
     */
    protected ?bool $is_alcohol;

    /**
     * Потребление мяса
     *
     * @ORM\Column(type="boolean", nullable=true)
     * Assert\NotNull(message="This value is not valid.")
     */
    protected ?bool $is_meat_consumption;

    /**
     * @ORM\ManyToOne(targetEntity="City")
     */
    protected ?City $city = null;

    public function __construct()
    {
        parent::__construct();

        $this->level            = 1;
        $this->is_alcohol       = null;
        $this->is_meat_consumption = null;
        $this->is_smoking       = null;
        $this->sex              = self::SEX_NA;
    }

    // Start SEX block of setters and getters

    static public function getSexFormChoices(): array
    {
        return array_flip(self::$sex_values);
    }

    static public function getSexValues(): array
    {
        return self::$sex_values;
    }

    static public function isSexExist($sex): bool
    {
        if (isset(self::$sex_values[$sex])) {
            return true;
        }

        return false;
    }

    public function getSexAsText(): string
    {
        if (isset(self::$sex_values[$this->sex])) {
            return self::$sex_values[$this->sex];
        }

        return 'N/A';
    }

    public function getSex(): int
    {
        return $this->sex;
    }

    public function setSex(?int $sex): self
    {
        $this->sex = $sex;

        return $this;
    }

    // __End SEX block of setters and getters

    public function getIsSmoking(): ?bool
    {
        return $this->is_smoking;
    }

    public function setIsSmoking(?bool $is_smoking): self
    {
        $this->is_smoking = $is_smoking;

        return $this;
    }

    public function getIsAlcohol(): ?bool
    {
        return $this->is_alcohol;
    }

    public function setIsAlcohol(?bool $is_alcohol): self
    {
        $this->is_alcohol = $is_alcohol;

        return $this;
    }

    public function getIsMeatConsumption(): ?bool
    {
        return $this->is_meat_consumption;
    }

    public function setIsMeatConsumption(?bool $is_meat_consumption): self
    {
        $this->is_meat_consumption = $is_meat_consumption;

        return $this;
    }

    public function getLevel(): int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }
}

templates/user/_anketa.html.twig
{% if is_user_form %}
    {% if user.isSmoking is not null %}
        {% if user.isSmoking %}
            <span class="badge badge-danger" title="Курит"><i class="fas fa-smoking"></i></span>
        {% else %}
            <span class="badge badge-light" title="Не курит"><i class="fas fa-smoking-ban"></i></span>
        {% endif %}
    {% endif %}

    {% if user.isAlcohol is not null %}
        {% if user.isAlcohol %}
            <span class="badge badge-danger" title="Потребяет алкоголь"><i class="fas fa-wine-bottle"></i></span>
        {% else %}
            <span class="badge badge-light" title="Не потребяет алкоголь"><i class="fas fa-wine-bottle"></i></span>
        {% endif %}
    {% endif %}

    {% if user.isMeatConsumption is not null %}
        {% if user.isMeatConsumption %}
            <span class="badge badge-danger" title="Потребяет мясо"><i class="fas fa-drumstick-bite"></i></span>
        {% else %}
            <span class="badge badge-light" title="Не потребяет мясо"><i class="fas fa-drumstick-bite"></i></span>
        {% endif %}
    {% endif %}
{% endif %}

templates/user/_layout.html.twig
{% extends 'base.html.twig' %}

{% block title %}Мой профиль{% endblock %}

{% block content %}
    <h1>Мой профиль</h1>

    <div class="row">
        <div class="col-xl-2">
            {{ knp_menu_render('profile') }}
        </div>

        <div class="col">
            {% block profile_content '' %}
        </div>
    </div>
{% endblock %}

templates/user/geoposition.html.twig
{% extends 'user/_layout.html.twig' %}

{% block css %}
    {{ parent() }}
    <style type="text/css">
        #geocoding_form {
            margin: 0px auto 10px;
        }
        .find-me.btn:focus {
            border-color: transparent;
            outline: 0;
        }
        .no-browser-support {
            font-size: 18px;
            opacity: 0;
            display: none;
        }
        .coordinates b:first-child {
            margin-right: 15px;
        }
    </style>
{% endblock css %}

{% block profile_content %}
    <h2>Моё местоположение</h2>

    <p>Указывайте место, которое вам удобно для встреч для обмена, а не фактического проживания.</p>

    <form method="post" id="geocoding_form" class="form-horizontal">
        <div class="form-group form-row">
            <div class="col">
                <button type="button" id="find-me" class="btn btn-sm btn-outline-info">Определить автоматически</button>
            </div>
            <div class="col">
                <input type="text" id="form_latitude" value="{{ latitude }}" name="latitude" class="form-control">
            </div>
            <div class="col">
                <input type="text" id="form_longitude" value="{{ longitude }}" name="longitude" class="form-control">
            </div>
            <div class="col">
                <button type="submit" class="btn btn-success">Сохранить</button>
            </div>
        </div>
    </form>

    <p class="no-browser-support">Sorry, the Geolocation API isn't supported in Your browser.</p>

    <div id="mapdiv"></div>

{% endblock profile_content %}

{% block js %}
    {{ parent() }}
    <script>
      var mymap = L.map('mapdiv', { attributionControl:false }).setView([{{ latitude ? latitude : 55.03023587}}, {{ longitude ? longitude : 82.92034149 }}], 14);

      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        // __dummy
      }).addTo(mymap);

      var marker = L.marker([{{ latitude ? latitude : 55.03023587}}, {{ longitude ? longitude : 82.92034149 }}]).addTo(mymap);

      //marker.bindPopup("<b>Hello world!</b><br>I am a popup.").openPopup();
      //marker.bindPopup("<b>Hello world!</b><br>I am a popup.");

      mymap.on('move', function () {
        marker.setLatLng(mymap.getCenter());

        var position = marker.getLatLng();
        lat = Number(position['lat']).toFixed(12);
        lng = Number(position['lng']).toFixed(12);

        $('#form_latitude').attr('value', lat);
        $('#form_longitude').attr('value', lng);

        //console.log(mymap.getCenter());
      });

      mymap.on('zoomanim', function () {
        marker.setLatLng(mymap.getCenter());

        var position = marker.getLatLng();
        lat = Number(position['lat']).toFixed(12);
        lng = Number(position['lng']).toFixed(12);

        $('#form_latitude').attr('value', lat);
        $('#form_longitude').attr('value', lng);

        //console.log(mymap.getCenter());
      });

      {#
      // Dragend event of map for update marker position
      mymap.on('dragend', function(e) {
        var cnt = mymap.getCenter();
        var position = marker.getLatLng();
        lat = Number(position['lat']).toFixed(5);
        lng = Number(position['lng']).toFixed(5);
        console.log(position);
        //setLeafLatLong(lat, lng);
      });
        #}

      function noLocation() {
        alert(55555555);
      }

      var findMeButton = $('#find-me');

      // Check if the browser has support for the Geolocation API
      if (!navigator.geolocation) {
        findMeButton.addClass("disabled");
        $('.no-browser-support').addClass("visible");
      } else {
        findMeButton.on('click', function(e) {
          e.preventDefault();
          navigator.geolocation.getCurrentPosition(function(position) {
            // Get the coordinates of the current possition.
            var lat = position.coords.latitude;
            var lon = position.coords.longitude;

            // alert(lat + ' ' + lon);

            $('#form_latitude').attr('value', lat.toFixed(12));
            $('#form_longitude').attr('value', lon.toFixed(12));

            mymap.setView([lat.toFixed(12), lon.toFixed(12)], 15);

            // $('#mapdiv').empty()

            //renderDragableMap(position.coords.longitude, position.coords.latitude)

          });
          // }, noLocation, {timeout:10000});

          // alert(444444444);
        });
      }

    </script>

{% endblock js %}

templates/user/invited.html.twig
{% extends 'user/_layout.html.twig' %}

{% block profile_content %}
    <p>Всего: {{ app.user.invitedUsers|length }}</p>

    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>ФИО</th>
            <th>Метод</th>
            <th>Статус</th>
            <th>Дата создания</th>
            <th>Был в сети</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for user in app.user.invitedUsers %}
            <tr>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">{{ user }}</a>

                    {% if user.telegramUsername %}
                        <a href="tg://resolve?domain={{ user.telegramUsername }}">
                            <span title="Написать сообщение в Телеграм" style="float: right; color: Dodgerblue;">
                                <i class="fab fa-telegram-plane"></i>
                            </span>
                        </a>
                    {% endif %}

                    {% if user.longitude and user.latitude %}
                        <span style="float: right; color: Dodgerblue; margin-right: 4px;">
                            <i class="fa fa-map-marker-alt"></i>
                        </span>
                    {% endif %}
                </td>
                <td>
                    {% if user.invite %}
                        По ссылке-приглашению
                    {% else %}
                        Вручную
                    {% endif %}
                </td>
                <td>
                    {% if user.enabled %}
                        <span class="label label-success label-important">Активен</span>
                    {% else %}
                        <span class="label label-danger label-important">Не Активен</span>
                    {% endif %}
                </td>
                <td>{{ user.createdAt|format_datetime }}</td>
                <td>
                    {% if user.lastLogin is not empty %}
                        {{ user.lastLogin|format_datetime }}
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('profile_invited_reset_password', {'id': user.id}) }}" class="btn btn-sm btn-success">Сброс пароля</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock profile_content %}

templates/user/invited_reset_password.html.twig
{% extends 'user/_layout.html.twig' %}

{% block profile_content %}
    <h1>Восстановление пароля</h1>

    {% if user %}
        {% if user.telegramUsername %}
            <p>Для пользователя: <a href="{{ path('user_show', {'id': user.id}) }}">{{ user }}</a></p>

            <p>Ссылка действует в течении 1 часа</p>

            <table width="100%" style="margin-bottom: 12px;">
                <tr>
                    <td>
                        <input id="foo" class="form-control" value="{{ url('reset_password', {'token': user.confirmationToken}) }}" autofocus>
                    </td>
                    <td style="width: 200px;">
                        <button class="btn btn-success" data-clipboard-target="#foo" style="margin-left: 6px;">
                            Скопировать ссылку
                        </button>
                    </td>
                </tr>
            </table>
        {% else %}
            <div class="alert alert-danger">
                Сброс пароля возможен только пользователям с привязанным телеграмом
            </div>
        {% endif %}

    {% else %}

    {% endif %}

{% endblock profile_content %}

{% block js %}
    {{ parent() }}

    <script src="{{ asset('assets/clipboard.min.js') }}"></script>
    <script>
      var clipboard = new ClipboardJS('.btn');

      clipboard.on('success', function(e) {
        new PNotify({
          title: 'Ссылка скопирована в буфер обмена!',
          type: 'success'
        });
      });

      clipboard.on('error', function(e) {
        new PNotify({
          title: '{{ 'Error'|trans }}!',
          text: 'При копировании ссылки в буфер обмена',
          type: 'error'
        });
      });
    </script>
{% endblock js %}

templates/user/profile.html.twig
{% extends 'user/_layout.html.twig' %}

{% block profile_content %}
    {% if form is defined %}
        <p>
            {{ app.user.username }}

            {% include 'user/_anketa.html.twig' with {'user': app.user} %}
        </p>

        {{ form(form) }}
    {% endif %}
{% endblock profile_content %}

templates/user/telegram.html.twig
{% extends 'user/_layout.html.twig' %}

{% block profile_content %}
    {% if app.user.telegramUsername %}
        <h2>Телеграм</h2>

        <p><a href="tg://resolve?domain={{ app.user.telegramUsername }}">@{{ app.user.telegramUsername }}</a>
            - <a href="?remove" style="color: red;" onclick="return confirm('Вы уверены, что хотите отвязать телеграмм аккаунт?')">отключить</a>
        </p>
    {% else %}
        <h2>Подключение телеграм</h2>

        {% if app_tg_bot_name() is not empty %}
            <p>На данный момент, телеграм используется как средство коммуникации между участниками, а также уведомления о заявках и других событиях. По этому для работы в системе необходимо подключить ваш телеграм аккаунт.</p>

            <p>В первую очередь, убедитесь, что вы задали "Имя пользователя" в телеграме, это можно проверить, зайдя в телеграме в <b>Настройки</b>
                (это можно сделать, нажав на иконку "три черточки" слева-вверху), если "Имя пользователя" ещё не было создано, то впишите текст, следуя инструкциям, которые там напишет телеграм.</p>

            <p>Если неполучается это сделать с "наскоку", то загуглите, например так: <a href="https://www.google.com/search?q=как+задать+имя+пользователя+в+телеграм" target="_blank">как задать имя пользователя в телеграм</a></p>

            <p>Также настоятельно рекомендуется настроить приватность в телеграме таким образом, чтобы внешне было затруднительно идентифицировать с реальным человеком.
                Для этого стоит избегать указания реальных имён и фамилий, как в профиле, так и в "имени пользователя", а также в настройках конфиденциальность указать никому не показывать "номер телефона".
            </p>

            <p>Скопируйте код <b>{{ code }}</b></p>

            <p>Зайдите в чат бот в телеграме <a href="tg://resolve?domain={{ app_tg_bot_name() }}">@{{ app_tg_bot_name() }}</a> нажмите "старт", а затем вставьте скопированный ранее код.</p>

            <p id="valid_msg">Код действителен в течении <span id="countdown">05:00</span> минут</p>

            <script>
              function startTimer(duration, display) {
                var timer = duration, minutes, seconds;
                setInterval(function () {
                  minutes = parseInt(timer / 60, 10);
                  seconds = parseInt(timer % 60, 10);

                  minutes = minutes < 10 ? "0" + minutes : minutes;
                  seconds = seconds < 10 ? "0" + seconds : seconds;

                  if (minutes === '00' && seconds === '00') {
                      var validMsg = document.querySelector('#valid_msg');
                      validMsg.innerHTML = '{{ 'Code is out of date'|trans }} - <a href="{{ path('profile_telegram') }}" class="btn btn-primary">{{ 'reload page'|trans }}</a>';
                  } else {
                      display.textContent = minutes + ":" + seconds;
                  }

                  if (--timer < 0) {
                    //timer = duration;
                    timer = 0;
                  }
                }, 1000);
              }

              window.onload = function () {
                var seconds = {{ countdown }};
                var display = document.querySelector('#countdown');
                startTimer(seconds, display);
              };
            </script>
        {% else %}
            <p>Бот не подключен</p>
        {% endif %}
    {% endif %}
{% endblock profile_content %}